Nginx profile update
mitre/nginx-stigready-baseline pull request #2
Opened 2020-07-02 02:53 UTC by ntruong18

NGINX Profile based on the Web Server SRG Version 2 Release 3.

2020-07-02 15:17 UTC, aaronlippold requested changes
Please see the discussion/conversation section for general comments

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40791.rb
> +conf_path = input('conf_path')
call this directly in the file vs setting a local var.

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40791.rb
> +  desc  "rationale", ""
remove `nil` sub-description

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40791.rb
> +Array(nginx_conf_handle.params['http']).each do |http|
Any reason we are wrapping these in `Array(....)` objects?

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40792.rb
> +  desc  "check", "
remove

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40792.rb
> +  describe "Manual Check" do
This should be more descriptive.. a manual check of what ... does it communicate what the user needs to do and check? Perhaps something like:
`This test requires a Manual Review` ...
We should standardize this lang across all the controls

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40799.rb
> +conf_path = input('conf_path')
call the input directly in the control

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40799.rb
> +access_log_path = input('access_log_path')
same

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40799.rb
> +error_log_path = input('error_log_path')
same

2020-07-02 15:17 UTC, aaronlippold commented on controls/V-40799.rb
> +  desc  "check", "
remove

2020-07-16 17:36 UTC, aaronlippold requested changes
Please see review comments and lets do a screen share to agree on how we want to update things

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-40819.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
Please call input directly rather then making them local variables

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41600.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
call inputs directly in the control rather than making them a local instance variable

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41609.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
same as above

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41611.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
same as above

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41612.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
same as above

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41613.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
same as above

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41614.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
I don't understand this actually - why is the nginx_conf resource being used here?

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41615.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
nginx_config.conf_path returns this data correct?

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41616.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
same as above.

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41616.rb
> +  describe nginx_conf_handle do
The above comment will also change this - and also - what is the point of this? That we ensure the conf file exists?

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41617.rb
> +  nginx_conf_handle = nginx_conf(input('conf_path'))
Ok. This is repeated tests that are not useful - we need to remove this

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41620.rb
> +  end
This needs to be removed

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41668.rb
> +  end
remove

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41670.rb
> +    its('mode')  { should cmp '0750'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41670.rb
> +      its('mode')  { should cmp '0640'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41670.rb
> +      its('mode')  { should cmp '0640'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41671.rb
> +    its('mode')  { should cmp '0750'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41671.rb
> +    its('mode')  { should cmp '0640'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41672.rb
> +    its('mode')  { should cmp '0750'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41672.rb
> +    its('mode')  { should cmp '0640'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41672.rb
> +    its('mode')  { should cmp '0640'}
use the `more_perssive_than` matcher

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41674.rb
> +    data files. If there is not a backup and recovery process for the web server, this is a finding."
This sentence is way too long - work with @ejaronne or myself to consolidate it

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41693.rb
> +  end
Same as above

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41694.rb
> +  end
This needs to be removed or updated

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41696.rb
> +  end
This needs to be removed

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41700.rb
> +nginx_allowed_script_list = input('nginx_allowed_script_list')
Please call inputs directly

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41700.rb
> +  end
This needs to be removed or updated

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41700.rb
> +    end unless location.params["fastcgi_params"].nil?
wrap this in a standard `if/else` block for easier readability

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41703.rb
> +  end
The verbiage here needs to be slimmed down

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41704.rb
> +  end
This needs to be removed or updated

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41706.rb
> +  end
This needs to be removed or updated

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41706.rb
> +      end unless server.params["listen"].nil?
wrap this into a standard `if/else` block for easier readability

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41730.rb
> +  end
Again, remove or update

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41730.rb
> +      end unless server.params["ssl_verify_depth"].nil?
wrap this in a standard `if/else` block to make readability easier

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41731.rb
> +  end
This needs to be updated or removed

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41731.rb
> +      end unless server.params["ssl_certificate"].nil?
update this to use a standard `if/elsif/else` block

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41731.rb
> +      end unless server.params["ssl_certificate_key"].nil?
linked to above comment

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41738.rb
> +  end
This needs to be removed or updated

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41738.rb
> +    end unless server.params["ssl_protocols"].nil?
Move this to a standard `unless` block at the top of the function

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41745.rb
> +    validated, this is a finding."
This needs to be slimmed down and more concise

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41746.rb
> +  end
This needs to be updated or removed

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41746.rb
> +    end unless server.params["ssl_protocols"].nil?
Move the `unless` statement to the top of the block for readability

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41807.rb
> +    its('version') { should cmp > '1.11.0' }
This version number should be an `input` given that it will update over time

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41808.rb
> +    its('version') { should cmp > '1.11.0' }
This version number should be an `input` as it will change over time

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41808.rb
> +  NGINX web server versions after 1.11.0 have the $request_id embedded variable
We should also use the `nginx_version` input here as well so the text updates automatically as well

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41809.rb
> +    its('version') { should cmp > '1.11.0' }
use the nginx_version input here

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41810.rb
> +    its('version') { should cmp > '1.11.0' }
use the version input here

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41818.rb
> +    its('version') { should cmp > '1.11.0' }
use the Nginx version input here - 

WHY ARE we checking the NGINX version more than ONCE??

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41821.rb
> +    nginx_conf_handle = nginx_conf(input('conf_path'))
This should be fixed we shouldn't need a local variable here

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41833.rb
> +end
Again this needs to be updated or removed

2020-07-16 17:36 UTC, aaronlippold commented on controls/V-41852.rb
> +  end
same as above

2020-07-28 23:21 UTC, aaronlippold commented on Gemfile
> +gem 'kitchen-sharedtests'
Do we actually need these gems?

2020-07-28 23:21 UTC, aaronlippold commented on README.md
> +# Web Server SRG Verson 2 Release 3 InSpec profile for nginx 1.19
Do we have any docs on testing or running the test suite ?

2020-07-28 23:21 UTC, aaronlippold commented on README.md
> +$ inspec exec nginx-srg-baseline -t example.com --user root --password=Pa55w0rd --input-file=srg-inputs.yml --reporter cli json:output.json
update the srg-inputs to the basic `inputs.yml` or if needed `inputs.vanilla.yml` and `inputs.hardened.yml`

2020-07-28 23:21 UTC, aaronlippold commented on Gemfile
> +gem 'inspec'
I think all we really need is inspec-bin right?

2020-07-28 23:21 UTC, aaronlippold commented on Gemfile
> +gem 'kitchen-sync'
are we using the transport-rysnc or the kitchen-sync?

2020-07-28 23:21 UTC, aaronlippold commented on README.md
>  - [ruby](https://www.ruby-lang.org/en/) version 2.4  or greater
I think the actually required ruby-2.6 or ruby-2.7 now

2020-07-28 23:21 UTC, aaronlippold commented on controls/V-41810.rb
> +  its('version') { should cmp == input('nginx_version') }
This should be `cmp > 1.11.0` given they say versions after `1.11.0` have this enabled by default.

2020-07-28 23:21 UTC, aaronlippold commented on controls/V-41818.rb
> +  If it is determined that the web server is not required to perform session management,
We need a boolean input here that will allow us to account for this NA case.

2020-07-28 23:21 UTC, aaronlippold commented on controls/V-41818.rb
> +    its('version') { should cmp == input('nginx_version') }
This seems like a repeat of another test and it again should cmp > 1.11.0 etc.

2020-07-28 23:21 UTC, aaronlippold commented on controls/V-41852.rb
> +        end unless http["charset"].nil?
This loop within a loop with an exit condition is very confusing and likely will result in a logic breakdown. All controls with this structure should be put on a list and re-reviewed to update the logic to ensure we have the best approach.

 I will let them slide for the first merge, as long as we create a 'review logic on controls' with a list of these.

2020-07-28 23:21 UTC, aaronlippold commented on controls/V-41854.rb
>  control "V-41854" do
There seems to be a missing NA condition here, what if there are no things defined? Is this a fail or an NA?

2020-07-29 15:19 UTC, aaronlippold commented on controls/V-40792.rb
> +  If it is not configured, this is a finding.
How does NGINX do Server Side Session Management

2020-07-29 15:45 UTC, aaronlippold commented on controls/V-41670.rb
> +
call inputs directly

2020-07-29 16:01 UTC, aaronlippold commented on controls/V-41672.rb
> +
call inputs directly

2020-08-01 17:18 UTC, aaronlippold commented on controls/V-41670.rb
> +
nevermind you are but creating a local instance variable with a combined data set - this is fine

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56003.rb
> +approved_ssl_protocols = input('approved_ssl_protocols')
Remove

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56005.rb
> +    its('version') { should cmp == input('nginx_version') }
cmp >=1.3.2

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-61353.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56035.rb
> +  nginx_conf.http.entries.each do |http|
NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56033.rb
> +    its('version') { should cmp == input('nginx_version') }
Add nginx_latest input

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56027.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56025.rb
> +  if nginx_conf.locations.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56023.rb
> +    its('version') { should cmp == input('nginx_version') }
change

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56017.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56015.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56013.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56011.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56009.rb
> +  if nginx_conf.locations.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56007.rb
> +  if nginx_conf.locations.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56003.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-56001.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55999.rb
> +  authorized_sa_user_list = input('sys_admin').clone << input('nginx_owner')
call input directly

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55997.rb
> +  nginx_conf.servers.each do |server|
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55995.rb
> +  if users.shells(/bash/).usernames.empty?
cover other shells

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55993.rb
> +  if users.shells(/bash/).usernames.empty?
cover other shells

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55991.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55989.rb
> + nginx_conf.locations.each do |location|
Add NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55987.rb
> +  if service_accounts.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55985.rb
> +  if nginx_conf.servers.empty?
Move up into NA statement.

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55981.rb
> +  if webserver_roots.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55979.rb
> +  describe "In the nginx.conf file" do
Remove

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55977.rb
> +  nginx_conf.params['http'].each do |http|
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55971.rb
> +  desc  "check", "
check if logging is configured

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55961.rb
> +  if nginx_conf.locations.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55959.rb
> +  describe "This test requires a Manual Review: Work with SIEM administrator
add input minimum_logging_file_size = 25G by default

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55957.rb
> +  describe "This test requires a Manual Review: Determine if the web server is part
Add input is_cluster and is_master

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55953.rb
> +  if nginx_conf.locations.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55951.rb
> +  nginx_conf.params['http'].each do |http|
Add NA statement for contexts

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55949.rb
> +  nginx_conf.params['http'].each do |http|
Add NA statement for contexts

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55947.rb
> +    if webserver_roots.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-55945.rb
> +    nginx_conf.locations.each do |location|
Add NA statement for contexts

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-41854.rb
> +  nginx_conf.params['http'].each do |http|
Add NA statement for contexts

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-41821.rb
> +    if webserver_roots.empty?
Add NA statement

2020-08-03 14:35 UTC, ntruong18 commented on controls/V-41833.rb
> +  nginx_conf.params['http'].each do |http|
Add NA statement for contexts

2020-08-03 19:33 UTC, ntruong18 commented on README.md
> +# Web Server SRG Verson 2 Release 3 InSpec profile for nginx 1.19
Added section to README

2020-08-03 19:34 UTC, ntruong18 commented on Gemfile
> +gem 'kitchen-sync'
Cleaned up Gemfile

2020-08-03 19:34 UTC, ntruong18 commented on controls/V-41854.rb
>  control "V-41854" do
Added NA condition

2020-08-05 01:42 UTC, aaronlippold approved these changes

2020-08-05 01:42 UTC, merged