Update workflows to use actions v4 and replace the archived workflow …
mitre/nginx-stigready-baseline pull request #20
Opened 2024-12-12 21:45 UTC by jtquach1

…actions/setup-ruby@v1 with ruby/setup-ruby@v1

Updating actions v3 to v4 since v3 will be deprecated 1/30/2025

2025-01-14 21:33 UTC, Amndeep7 requested changes

2025-01-14 21:33 UTC, Amndeep7 commented on .github/workflows/verify-docker.yml
>            ruby-version: "2.7"
please update to ruby 3.x

2025-01-14 21:34 UTC, Amndeep7 commented
the docker one claims that it's passing, but it is actually also failing
![image](https://github.com/user-attachments/assets/65cbfbc8-c86b-420d-8d18-52b3ba913764)

2025-01-14 21:49 UTC, jtquach1 commented on .github/workflows/verify-docker.yml
>            ruby-version: "2.7"
done

2025-01-15 06:14 UTC, Amndeep7 approved these changes
Fixed problems with everything other than the ec2 profile failing due to the vpc issue which is already being tracked by Daniel

2025-01-15 06:14 UTC, merged